type_of_alcohol = input("what did you drink today: ")
number= float(input("how many? "))
place = input("with whom did you went to strip club: ")
members = input("how many members: ")
thing = input("ended up sleeping with: ")
day = input("how was the day: ")
mood = input("were you happy in the end?")
spent = float(input("how much did you guys spent? "))
spent = int(spent)
number = int(number)
print(f"Today i drank {number}{type_of_alcohol} ")
print(f"Then, i went to strip club with my {place} of {members} members to have some fun")
print(f"but ended up fucking a {thing}")
print(f"Came back home having {day} day")
print(f"now, im so {mood} in my life")
print(f"but, the sad part is we ended up spending {spent}")