#name = input("enter your full name: ")
#phone_no = input("enter ur phone no.: ")
#result = len(name)
#result = name.find(" ")
#result = name.rfind("i")
#result = name.capitalize()
#result = name.upper()
#result = name.lower()
#result = name.isdigit()
#result = name.isalpha()
#result = phone_no.count("0")
#result= phone_no.replace("0", "5")
#print(result)
creditcardno = "4035 0070 6214 6004"
#print(creditcardno[0:4])
#print(creditcardno[8:34])
#print(creditcardno[-9])
print(creditcardno[::3])